### ISSUE TITLE
setUserId creating anonymous users. Also a request to add more setUser features

### ISSUE THREAD

**Issue by rynhrn** [MindscapeHQ/raygun4flutter#1]
Hello,

Currently the setUserId is the only function for creating users and is creating them as anonymous users in the Raygun dashboard, even with an ID provided. 

Also would it be possible to for you to add the name and email options when creating users? 
Would be really good to have these features.

Thanks!

**Comment by TheRealAgentK** [comment]
Hi @rynhrn - the RG4Flutter provider is still quite experimental and `alpha` at this stage.

Just wondering, did you experience this on one particular platform, e.g. Android or iOS only. Trying to ascertain if this bubbles up from an issue in one of the underlying native libs.

**Comment by miquelbeltran** [comment]
> Also would it be possible to for you to add the name and email options when creating users?

This can definitely be done. I will create a different GitHub ticket for that.

**Comment by thogg4** [comment]
This might be addressed by #3

**Comment by TheRealAgentK** [comment]
@thogg4 Yeah, it will be. I'll close this ticket and leave #2 open.
