### ISSUE TITLE
Doc: UserInfo -> identifier required

### ISSUE THREAD

**Issue by TheRealAgentK** [MindscapeHQ/raygun4flutter#16]
this param becomes non-nullable because it is required for iOS, even if Android allow nulls here

_Originally posted by @miquelbeltran in https://github.com/MindscapeHQ/raygun4flutter/pull/15#r681229111_

**Comment by TheRealAgentK** [comment]
Ok, but what still works is this, right?

---
`Raygun.setUserId('1234');`
Call with id null to clear the user identifier.
---

It seems that passing in null there will on iOS do this:  RaygunUserInformation.anonymousUser

Is there a reason why the same doesn't happen if no identifier is passed into a RaygunUserInfo object?

**Comment by miquelbeltran** [comment]
the iOS Swift implementation does not support a `RaygunUserInfo` with a null ID, for example something like:

```
RaygunUserInfo (
  id: null,
  firstname: 'Max',
  // etc
)
```

If a user wants to set the user back to anonymous they can either call `Raygun.setUserId(null);` or `Raygun.setUser(null);` which is handled the same internally.
