### ISSUE TITLE
Test on Windows 10

### ISSUE THREAD

**Issue by miquelbeltran** [MindscapeHQ/raygun4flutter#44]

**Comment by TheRealAgentK** [comment]
Prrrrettty sure @CmdrKeen has a Windows 11 system somewhere.... <wink wink>

**Comment by CmdrKeen** [comment]
What's the best way to test this @miquelbeltran ? Happy to try it out :-)

**Comment by miquelbeltran** [comment]
I tested the Windows 10 support and it works (only a minor issue had to be fixed).

I have no idea if Windows 11 is even supported by Flutter :) If you want to try, you'll have to follow all the Flutter setup steps and then run the desktop example app. 

- https://flutter.dev/docs/get-started/install
- To enable desktop: https://flutter.dev/desktop
- Then to run the example, go into the example project and run `flutter run` selecting Windows as the target.
- Finally tap some of the buttons on the screen and see if any errors appear in the debug console.
